config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get 'contact' , to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :izakayas, only: %i[index show] do
    collection do
      get :favorites
    end
  end
  resources :favorites, only: %i[create destroy]

  resources :izakaya_plans, only: [:create, :destroy] do
    patch "reorder", on: :member
  end
  resources :plans

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :izakaya

  validates :user_id, uniqueness: { scope: :izakaya_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @izakaya = Izakaya.find(params[:izakaya_id])
    current_user.favorite(@izakaya)

    respond_to do |format|
      format.html { redirect_to izakayas_path }
      format.turbo_stream
    end
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id])
    if favorite
      @izakaya = favorite.izakaya
      current_user.unfavorite(@izakaya)

      respond_to do |format|
        format.html { redirect_to izakayas_path, status: :see_other }
        format.turbo_stream
      end
    else
      redirect_to izakayas_path, alert: 'Favorite not found'
    end
  end
end

app/views/favorites/_favorite.html.erb
<%= link_to favorites_path(izakaya_id: izakaya.id), id: "favorite-button-for-izakaya-#{izakaya.id}", data: { "turbo-method": :post } do %>
  <i class="fa-regular fa-heart"></i>
<% end %>

app/views/favorites/_favorite_button.html.erb
<div id ="favorite_<%= izakaya.id %>">
<% if current_user.favorite?(izakaya) %>
    <%= render 'favorites/unfavorite', izakaya: izakaya %>
  <% else %>
    <%= render 'favorites/favorite', izakaya: izakaya %>
  <% end %>
</div>

app/views/favorites/_favorites.html.erb
<%= link_to izakaya_path(favorites.izakaya) do %>
  <div class="m-4 p-4 rounded-lg shadow-md" style="background-image: url('<%= favorites.izakaya.image %>'); background-size: cover; background-position: center;">
    <h3 class="text-lg font-semibold text-white bg-slate-950 opacity-70"><%= favorites.izakaya.name %></h3>
  </div>
<% end %>

app/views/favorites/_unfavorite.html.erb
<%= link_to favorite_path(izakaya.favorites.find { |f| f.user_id == current_user.id }), id: "unfavorite-button-for-izakaya-#{izakaya.id}", data: { turbo_method: :delete } do %>
  <i class="fa-solid fa-heart"></i>
<% end %>

app/views/favorites/create.turbo_stream.erb
<%= turbo_stream.replace "favorite-button-for-izakaya-#{@izakaya.id}" do %>
  <%= render 'favorites/unfavorite', izakaya: @izakaya %>
<% end %>

app/views/favorites/destroy.turbo_stream.erb
<%= turbo_stream.replace "unfavorite-button-for-izakaya-#{@izakaya.id}" do %>
  <%= render 'favorites/favorite', izakaya: @izakaya %>
<% end %>