config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get 'contact' , to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :izakayas, only: %i[index show] do
    collection do
      get :favorites
    end
  end
  resources :favorites, only: %i[create destroy]

  resources :izakaya_plans, only: [:create, :destroy] do
    patch "reorder", on: :member
  end
  resources :plans

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_before_login_header.erb
<header class="fixed top-0 left-0 w-full z-10 text-white">
  <div class="flex items-center justify-between">
    <div class="flex items-center text-base md:text-2xl">
      <a href="/" class="text-base md:text-2xl font-bold ml-2 p-2"><%= t('header.title') %></a>
      <%= link_to 'JP', url_for(locale: :ja), class: "text-xs py-2 px-2" %> /
      <%= link_to 'EN', url_for(locale: :en), class: "text-xs py-2 px-2" %>
    </div>
    <div class="block">
      <%= link_to auth_at_provider_path(provider: :google), class: "flex items-center py-2 px-4" do %>
        <%= image_tag 'web_dark_rd_na.svg', alt: 'Google Logo', class: 'mr-2' %>
        <%= t('header.login') %>
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_flash_message.html.erb
<div class="pt-16">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="fixed bottom-0 left-0 right-0 text-white">
  <div class="flex items-center justify-between">
    <nav class="lg:flex items-center mb-4">
      <% footer_links = [
        { path: contact_path, text: t('footer.contact') },
        { path: terms_path, text: t('footer.terms_of_use') },
        { path: privacy_policy_path, text: t('footer.privacy_policy') }
      ] %>
      <% footer_links.each do |link| %>
        <a href="<%= link[:path] %>" class="text-xs font-bold ml-2"><%= link[:text] %></a>
      <% end %>
    </nav>
    <div class="flex items-center">
      <a href="https://x.com/intent/tweet?text=<%= CGI.escape("#{t('footer.tag')} https://nishinari-izakaya.net") %>" class="mr-2 mb-4" target="_blank" rel="noopener noreferrer">
        <img src="<%= asset_path('x-logo.svg') %>" alt="X Logo" />
      </a>
      <span class="text-xs font-bold mr-2 mb-4"><%= t('footer.title') %></span>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="fixed top-0 left-0 w-full z-10 text-white">
  <div class="flex items-center justify-between">
    <div class="flex items-center text-base md:text-2xl">
      <a href="/" class="text-base md:text-2xl font-bold ml-2 p-2"><%= t('header.title') %></a>
      <%= link_to 'JP', url_for(locale: :ja), class: "text-xs py-2 px-2" %> /
      <%= link_to 'EN', url_for(locale: :en), class: "text-xs py-2 px-2" %>
    </div>
    <div class="block mr-1">
      <%= link_to t('header.mypage'), profile_path %> /
      <%= link_to t('header.logout'), logout_path, data: { turbo_method: :delete } %>
    </div>
  </div>
</header>