config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get 'contact' , to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :izakayas, only: %i[index show] do
    collection do
      get :favorites
    end
  end
  resources :favorites, only: %i[create destroy]

  resources :izakaya_plans, only: [:create, :destroy] do
    patch "reorder", on: :member
  end
  resources :plans

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/izakaya.rb
class Izakaya < ApplicationRecord
  has_many :izakaya_tags
  has_many :tags, through: :izakaya_tags
  has_many :izakaya_plans
  has_many :plans, through: :izakaya_plans
  has_many :favorites, dependent: :destroy
end

app/controllers/izakayas_controller.rb
class IzakayasController < ApplicationController
  skip_before_action :require_login

  def index
    @tags = Tag.order(id: :asc).all
    selected_tags = params[:q] ? params[:q][:tags_id_all] : []

    if selected_tags.present?
      izakaya_ids = Izakaya.joins(:tags)
                           .where(tags: { id: selected_tags })
                           .group('izakayas.id')
                           .having('COUNT(tags.id) = ?', selected_tags.size)
                           .pluck(:id)
      @q = Izakaya.where(id: izakaya_ids).ransack(params[:q])
    else
      @q = Izakaya.ransack(params[:q])
    end

    # 現在地からの距離を計算して、10件取得する
    if params[:lat].present? && params[:lng].present?
      lat1 = params[:lat].to_f * Math::PI / 180
      lng1 = params[:lng].to_f * Math::PI / 180

      arounds = Izakaya.all.map do |izakaya|
        lat2 = izakaya.lat * Math::PI / 180
        lng2 = izakaya.lng * Math::PI / 180

        diff_y = (lng1 - lng2).abs
        calc1 = Math.cos(lat2) * Math.sin(diff_y)
        calc2 = Math.cos(lat1) * Math.sin(lat2) - Math.sin(lat1) * Math.cos(lat2) * Math.cos(diff_y)

        numerator = Math.sqrt(calc1 ** 2 + calc2 ** 2)
        denominator = Math.sin(lat1) * Math.sin(lat2) + Math.cos(lat1) * Math.cos(lat2) * Math.cos(diff_y)
        degree = Math.atan2(numerator, denominator)

        α = 6378.137
        distance = degree * α

        { izakaya: izakaya, distance: distance }
      end

      @izakayas = arounds.sort_by { |h| h[:distance] }.first(10).map { |h| h[:izakaya] }
    else
      @izakayas = @q.result(distinct: true).includes(:tags, :favorites).order(id: :asc)
    end

    @plan_exists = current_user ? Plan.exists?(user_id: current_user.id) : false
  end

  def show
    @izakaya = Izakaya.find(params[:id])
    @tags = Tag.order(id: :asc).all
  end

  def favorites
    @q = current_user.favorites_izakayas.ransack(params[:q])
    @favorite_izakayas = @q.result(distinct: true).includes(:user).order(created_at: :desc)
  end
end

app/views/izakayas/index.html.erb
<div class="container mx-auto pt-16 pb-4">
  <button id="toggleSearch" class="bg-zinc-500 hover:bg-zinc-700 text-white p-2 ml-4 rounded"><%= t('.search_by_name') %></button>

  <div id="searchContainer" style="display: none;">
    <%= search_form_for @q, url: izakayas_path, method: :get, class: "mb-4" do |f| %>
      <div class="flex flex-wrap items-center">
        <div class="w-full md:w-1/2 mb-4 md:mb-0 text-white">
          <%= f.text_field :name_cont, class: "input input-bordered w-full" %>
        </div>
        <div class="w-full md:w-1/2 mb-4 md:mb-0 md:ml-4 flex flex-col md:flex-row items-center">
          <%= f.submit t('.search'), class: "btn bg-zinc-500 hover:bg-zinc-700 text-white w-full md:w-auto mb-2 md:mb-0 md:mr-2" %>
          <%= link_to t('.clear_search'), izakayas_path, class: 'btn bg-rose-500 hover:bg-rose-300 text-white w-full md:w-auto' %>
        </div>
      </div>
    <% end %>
  </div>

  <button id="toggleTags" class="bg-zinc-500 hover:bg-zinc-700 text-white p-2 ml-4 rounded"><%= t('.search_by_tags') %></button>
  <div id="tagSearchContainer" class="flex flex-wrap gap-2" style="display: none;">
    <% selected_tags = Array(params.dig(:q, :tags_id_all)) %>
    <% @tags.each do |tag| %>
      <% is_selected = selected_tags.include?(tag.id.to_s) %>
      <% new_selected_tags = is_selected ? selected_tags - [tag.id.to_s] : selected_tags + [tag.id.to_s] %>
      <%= link_to izakayas_path(q: { tags_id_all: new_selected_tags.uniq }), class: "inline-block #{is_selected ? 'bg-green-500 hover:bg-green-700' : 'bg-zinc-500 hover:bg-zinc-700'} text-white text-xs px-3 py-1 rounded-full" do %>
        <%= tag.name %>
      <% end %>
    <% end %>
  </div>
  <% if selected_tags.any? %>
    <div class="mt-4">
      <span class="inline-block bg-rose-500 hover:bg-rose-300 text-white text-xs px-3 py-1 rounded-full">
        <%= link_to t('.clear_narrow_down'), izakayas_path %>
      </span>
    </div>
  <% end %>

  <div>
    <button id="toggleMap" class="bg-zinc-500 hover:bg-zinc-700 text-white p-2 ml-4 my-2 rounded"><%= t('.show_map') %></button>
    <div id="map" style="height: 500px; display: none;"></div>
  </div>

  <button onclick="getLocationAndSubmit()" id="get-button" class="bg-zinc-500 hover:bg-zinc-700 text-white p-2 ml-4 mx-2 rounded"><%= t('.search_nearby') %></button>
  <%= form_tag({controller:"izakayas",action:"index"}, method: :get, id: "location-form") do %>
    <%= hidden_field_tag :lat, nil, id: :lat %>
    <%= hidden_field_tag :lng, nil, id: :lng %>
  <% end %>
</div>

<script>
  document.getElementById('toggleSearch').addEventListener('click', function() {
    const searchContainer = document.getElementById('searchContainer');
    if (searchContainer.style.display === 'none') {
      searchContainer.style.display = 'block';
      this.textContent = '<%= t('.hide_search_by_name') %>';
    } else {
      searchContainer.style.display = 'none';
      this.textContent = '<%= t('.search_by_name') %>';
    }
  });

  document.getElementById('toggleTags').addEventListener('click', function() {
    const tagSearchContainer = document.getElementById('tagSearchContainer');
    if (tagSearchContainer.style.display === 'none') {
      tagSearchContainer.style.display = 'block';
      this.textContent = '<%= t('.hide_search_by_tags') %>';
    } else {
      tagSearchContainer.style.display = 'none';
      this.textContent = '<%= t('.search_by_tags') %>';
    }
  });

  document.getElementById('toggleMap').addEventListener('click', function() {
    const mapElement = document.getElementById('map');
    if (mapElement.style.display === 'none') {
      mapElement.style.display = 'block';
      initMap();
      this.textContent = '<%= t('.hide_map') %>';
    } else {
      mapElement.style.display = 'none';
      this.textContent = '<%= t('.show_map') %>';
    }
  });

  function initMap() {
    const mapElement = document.getElementById('map');

    const mapOptions = {
      center: { lat: 34.6492213, lng: 135.5033723 },
      zoom: 16
    };

    const map = new google.maps.Map(mapElement, mapOptions);

    const izakayas = <%= raw @izakayas.to_json %>;

    izakayas.forEach(izakaya => {
      let marker = new google.maps.Marker({
        position: {lat: izakaya.lat, lng: izakaya.lng},
        map: map,
        title: izakaya.name
      });

      google.maps.event.addListener(marker, 'click', function() {
        window.location.href = `/izakayas/${izakaya.id}`;
      });
    });
  }

  function getLocationAndSubmit() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(showPositionAndSubmit);
    } else {
      alert("Geolocation is not supported by this browser.");
    }
  }

  function showPositionAndSubmit(position) {
    document.getElementById('lat').value = position.coords.latitude;
    document.getElementById('lng').value = position.coords.longitude;
    document.getElementById('location-form').submit();
  }
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLEMAPS_API_KEY"] %>&callback=initMap"></script>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 pb-16 text-white">
  <% @izakayas.each do |izakaya| %>
    <div class="card shadow-lg compact bg-base-100">
      <div class="card-body bg-slate-700">
        <h2 class="card-title">
          <%= link_to izakaya.name, izakaya_path(izakaya) %>
        </h2>
        <%= link_to izakaya_path(izakaya) do %>
          <img src="<%= izakaya.image %>" alt="<%= izakaya.name %>" class="w-full h-auto object-contain max-h-48">
        <% end %>
        <p>
          <% izakaya.tags.sort_by(&:id).each do |tag| %>
            <span class="inline-block bg-zinc-500 hover:bg-zinc-700 text-white text-xs px-3 py-1 mt-1 rounded-full">
              <%= tag.name %>
            </span>
          <% end %>
        </p>
        <% if current_user && @plan_exists %>
          <%= form_with url: izakaya_plans_path, method: :post, local: true do |form| %>
            <%= form.hidden_field 'izakaya_plan[izakaya_id]', value: izakaya.id %>
            <%= form.collection_select 'izakaya_plan[plan_id]', current_user.plans, :id, :name, prompt: t('.select_plan') %>
            <%= form.submit t('.add_izakaya'), class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
          <% end %>
        <% end %>
        <% if current_user %>
        <div id="favorite_izakaya_<%= izakaya.id %>_button">
          <%= render 'favorites/favorite_button', izakaya: izakaya %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/izakayas/show.html.erb
<div class="flex justify-center items-center pt-16 pb-4 text-slate-800">
  <div class="bg-white p-6 rounded-lg w-3/4">
    <h2 class="card-title text-lg md:text-2xl font-bold mb-4"><%= @izakaya.name %></h2>
    <img src="<%= @izakaya.image %>" alt="<%= @izakaya.name %>" class="w-full h-auto rounded-md mb-4 object-contain max-h-72">
    <p>
      <% @izakaya.tags.sort_by(&:id).each do |tag| %>
        <span class="inline-block bg-zinc-500 hover:bg-zinc-700 text-white text-xs px-3 py-1 my-1 rounded-full">
          <%= tag.name %>
        </span>
      <% end %>
    </p>
    <p class="mb-4">
      <%= link_to t('.google_map'), @izakaya.url, target: "_blank", class: "btn btn-sm text-white m-1" %>
      <%= link_to t('.direction_search'), "https://www.google.com/maps/dir/?api=1&destination=#{@izakaya.lat},#{@izakaya.lng}", target: "_blank", class: "btn btn-sm text-white m-1" %>
      <%= link_to t('.youtube_search'), "https://www.youtube.com/results?search_query=#{ERB::Util.url_encode("西成 " + @izakaya.name)}", target: "_blank", class: "btn btn-sm text-white m-1" %>
    </p>
    <p class="text-sm mb-4"><%= @izakaya.description %></p>
  </div>
</div>