config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'static_pages#top'
  get 'contact' , to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms'
  get 'privacy_policy', to: 'static_pages#privacy_policy'

  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  resources :izakayas, only: %i[index show] do
    collection do
      get :favorites
    end
  end
  resources :favorites, only: %i[create destroy]

  resources :izakaya_plans, only: [:create, :destroy] do
    patch "reorder", on: :member
  end
  resources :plans

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :izakaya_plans, dependent: :destroy
  has_many :izakayas, through: :izakaya_plans
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :set_plan, only: %i[show edit update destroy]

  def index
    @plans = Plan.includes(:izakayas).where(public: true).or(Plan.where(user: current_user))
  end

  def show
    @plan = Plan.find(params[:id])
    unless current_user&.own?(@plan) || @plan.public?
      redirect_to plans_path, alert: t('.plans.public_false')
    end
    @izakayas = @plan.izakayas.joins(:izakaya_plans).merge(IzakayaPlan.rank(:row_order))
    @izakaya_plan = IzakayaPlan.find_by(plan: @plan)

    set_meta_tags({
      title: '西成泥酔旅行',
      og: {
        title: '西成泥酔旅行',
        url: request.original_url,
      }
    })
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.user = current_user

    if @plan.save
      redirect_to @plan, notice: t('.success')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @plan.update(plan_params)
      redirect_to @plan, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @plan.destroy!
    redirect_to plans_path, success: t('.success'), status: :see_other
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:name, :public, :description)
  end
end

app/views/plans/_plan.html.erb
<%= link_to plan_path(plan) do %>
  <div class="m-4 p-4 rounded-lg shadow-md <%= plan.izakayas.first ? 'bg-cover' : 'bg-gray-300' %>" style="background-image: url('<%= plan.izakayas.first ? plan.izakayas.first.image : 'izakaya' %>');">
    <h3 class="text-lg font-semibold text-white bg-slate-950 opacity-70"><%= plan.name %></h3>
  </div>
<% end %>

app/views/plans/edit.html.erb
<div class="pt-16 pb-4 text-white">
  <%= form_with(model: @plan, local: true, class: 'max-w-lg mx-auto p-4 bg-white shadow-md rounded-lg') do |f| %>
    <div class="mb-4">
      <%= f.label :name, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= f.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="mb-4">
      <%= f.label :public, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= f.check_box :public, class: 'form-checkbox h-5 w-5 text-blue-600' %>
    </div>

    <div class="mb-4">
      <%= f.label :description, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= f.text_area :description, rows: 4, class: 'shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="flex items-center justify-between">
      <%= f.submit t('.submit'), class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
    </div>
  <% end %>
</div>
<div class="mt-4 ml-2">
  <%= link_to t('.back'), plans_path, class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
</div>

app/views/plans/index.html.erb
<div class="pt-16 pb-4">
  <% if logged_in? %>
    <%= link_to t('.create_plan'), new_plan_path, class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white m-4' %>
  <% else %>
    <%= link_to t('.create_plan_login'), auth_at_provider_path(provider: :google), class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white m-4' %>
  <% end %>
</div>
<ul class="flex flex-wrap justify-center">
<% @plans.each do |plan| %>
  <li class="m-4">
    <div class="card w-96 shadow-xl image-full my-4">
      <figure>
        <% if plan.izakayas.any? && plan.izakayas.first.image.present? %>
          <%= image_tag plan.izakayas.first.image, alt: 'izakaya' %>
        <% else %>
        <% end %>
      </figure>
      <div class="card-body">
        <div class="card-title text-2xl text-white"><%= plan.name %></div>
        <p></p>
        <div class="card-actions justify-end">
          <%= link_to t('.show'), plan_path(plan), class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
          <% if current_user&.own?(plan) %>
            <%= link_to t('.edit'), edit_plan_path(plan), class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
            <%= link_to t('.delete'), plan_path(plan), data: { turbo_method: :delete, turbo_confirm: t('.confirm_delete') }, class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
          <% end %>
        </div>
      </div>
    </div>
  </li>
<% end %>
</ul>

app/views/plans/new.html.erb
<div class="pt-16 pb-4 text-white">
  <%= form_with(model: @plan, local: true, class: 'max-w-lg mx-auto p-4 bg-white shadow-md rounded-lg') do |f| %>
    <div class="mb-4">
      <%= f.label :name, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= f.text_field :name, class: 'shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="mb-4">
      <%= f.label :public, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= f.check_box :public, class: 'form-checkbox h-5 w-5 text-blue-600' %>
    </div>

    <div class="mb-4">
      <%= f.label :description, class: 'block text-gray-700 text-sm font-bold mb-2' %>
      <%= f.text_field :description, class: 'shadow appearance-none border rounded w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline' %>
    </div>

    <div class="flex items-center justify-between">
      <%= f.submit t('.submit'), class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
    </div>
  <% end %>
</div>
<div class="mt-4 ml-2">
  <%= link_to t('.back'), plans_path, class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
</div>

app/views/plans/show.html.erb
<div class="pt-16 pb-4 pl-4">
  <h1 class="text-3xl font-bold mb-6 text-white"><%= @plan.name %></h1>
  <h2 class="text-xl font-bold mb-6 text-white"><%= @plan.description %></h2>
</div>
<% if current_user&.own?(@plan) %>
  <p class="mb-4 pl-4 text-white">
    <strong><%= t('.public') %> :</strong>
    <%= @plan.public ? t('.public_true') : t('.public_false') %>
  </p>
  <div class="flex space-x-4" >
    <% if @plan.public %>
      <div class="mb-4 pl-4">
        <%= link_to t('.x_share'), "https://x.com/intent/tweet?text=#{CGI.escape("#{@plan.name} #{t('.x_message')} #{plan_url(@plan)}")}", class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white', target: '_blank', rel: 'noopener noreferrer' %>
      </div>
    <% end %>
    <%= link_to t('.add_izakaya'), izakayas_path, class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
  </div>
  <p class="bg-zinc-500 rounded-full inline-block text-xs ml-4 mb-4 p-3 text-white"><%= t('.description')%></p>
<% end %>

<div
  id="izakayas"
  class="grid grid-cols-1 gap-4 md:max-w-lg max-w-xs mx-auto"
  <% if current_user&.own?(@plan) %>
    data-controller="sortable"
    data-sortable-handle-selector-value=".sortable-handle"
  <% end %>
>
  <% @plan.izakaya_plans.rank(:row_order).each do |izakaya_plan| %>
    <div
      id="<%= dom_id(izakaya_plan) %>"
      class="card bg-white shadow-md rounded-lg p-4 flex flex-col justify-center items-center md:max-h-72 max-h-44"
      style="background-image: url('<%= izakaya_plan.izakaya.image %>'); background-size: cover; background-position: center;"
      <% if current_user&.own?(@plan) %>
        data-sortable-url="<%= reorder_izakaya_plan_path(izakaya_plan) %>"
      <% end %>
    >
      <div class="card-body flex flex-col justify-between w-full items-center">
        <h3 class="card-title text-xl font-bold text-white bg-slate-950 opacity-70 p-2"><%= izakaya_plan.izakaya.name %></h3>
        <div class="flex space-x-2 mt-2">
          <%= link_to t('.show'), izakaya_path(izakaya_plan.izakaya), class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
          <% if current_user&.own?(@plan) %>
            <%= link_to t('.delete'), izakaya_plan_path(izakaya_plan), data: { turbo_method: :delete, turbo_confirm: t('.confirm_delete') }, class: 'btn bg-zinc-500 hover:bg-zinc-700 text-white' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>